// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOsRG8wHyRXb6ccMBU17cIJu_gZakoTsE',
    appId: '1:1095482003288:web:e6d856e8c52310c10b9f2d',
    messagingSenderId: '1095482003288',
    projectId: 'chatapp-3b4a6',
    authDomain: 'chatapp-3b4a6.firebaseapp.com',
    storageBucket: 'chatapp-3b4a6.firebasestorage.app',
    measurementId: 'G-GEEWD6S3XE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXk5Csm_C31fK81AgoGS_eKuMEYn2fON8',
    appId: '1:1095482003288:android:4e2d1ab97d0d7e980b9f2d',
    messagingSenderId: '1095482003288',
    projectId: 'chatapp-3b4a6',
    storageBucket: 'chatapp-3b4a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0onWJpM2zk0Wi0YkpU3ZsdmP1OvIk4m0',
    appId: '1:1095482003288:ios:a929ff46b00927d80b9f2d',
    messagingSenderId: '1095482003288',
    projectId: 'chatapp-3b4a6',
    storageBucket: 'chatapp-3b4a6.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0onWJpM2zk0Wi0YkpU3ZsdmP1OvIk4m0',
    appId: '1:1095482003288:ios:a929ff46b00927d80b9f2d',
    messagingSenderId: '1095482003288',
    projectId: 'chatapp-3b4a6',
    storageBucket: 'chatapp-3b4a6.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOsRG8wHyRXb6ccMBU17cIJu_gZakoTsE',
    appId: '1:1095482003288:web:91b28fea0095de2f0b9f2d',
    messagingSenderId: '1095482003288',
    projectId: 'chatapp-3b4a6',
    authDomain: 'chatapp-3b4a6.firebaseapp.com',
    storageBucket: 'chatapp-3b4a6.firebasestorage.app',
    measurementId: 'G-9V3HYBH491',
  );
}
